import type { EaForm } from "../services/tax.service";
import { A4, MARGIN, createPdf, drawFooters, money, pdfText } from "./common";

/** Borang EA (C.P.8A) as a true PDF. */
export async function eaPdf(ea: EaForm, footer?: string | null): Promise<Buffer> {
  const { doc, done } = createPdf({ title: `Borang EA ${ea.year} - ${ea.employee.name}`, author: ea.employer.name, subject: "Form EA" });
  const width = A4.width - MARGIN * 2;
  const fmt = (d: Date | null) => (d ? d.toLocaleDateString("en-GB", { day: "2-digit", month: "short", year: "numeric", timeZone: "UTC" }) : "-");

  doc.font("Helvetica-Bold").fontSize(8).fillColor("#666666").text("BORANG EA (C.P.8A) · PENYATA SARAAN DARIPADA PENGGAJIAN", MARGIN, MARGIN);
  doc.font("Helvetica-Bold").fontSize(16).fillColor("#111111").text(`Statement of Remuneration from Employment · Year ${ea.year}`, MARGIN, doc.y + 4, { width });
  doc.font("Helvetica").fontSize(8.5).fillColor("#555555").text(`Based on ${ea.months} month(s) of finalised payroll. Employers must issue Form EA by the last day of February ${ea.year + 1}.`, { width });
  let y = doc.y + 10;
  doc.moveTo(MARGIN, y).lineTo(A4.width - MARGIN, y).lineWidth(1.5).strokeColor("#111111").stroke();
  y += 12;

  const half = (width - 20) / 2;
  const block = (x: number, title: string, lines: string[]) => {
    doc.font("Helvetica-Bold").fontSize(8).fillColor("#777777").text(title, x, y, { width: half });
    doc.font("Helvetica").fontSize(9.5).fillColor("#111111");
    lines.forEach((l) => doc.text(pdfText(l), x, doc.y + 2, { width: half }));
    return doc.y;
  };
  const a = block(MARGIN, "A. PARTICULARS OF EMPLOYEE", [
    ea.employee.name,
    `NRIC: ${ea.employee.icNo ?? "-"}    Tax no.: ${ea.employee.taxNo ?? "-"}`,
    `EPF no.: ${ea.employee.epfNo ?? "-"}    SOCSO no.: ${ea.employee.socsoNo ?? "-"}`,
    `${ea.employee.jobTitle} · Staff no. ${ea.employee.employeeNo}`,
    `Employed ${fmt(ea.employee.joinDate)}${ea.employee.lastWorkingDate ? ` to ${fmt(ea.employee.lastWorkingDate)}` : ""}`,
  ]);
  const b = block(MARGIN + half + 20, "EMPLOYER", [ea.employer.name, `Employer no. (E): ${ea.employer.taxNo ?? "-"}`, ea.employer.address ?? ""]);
  y = Math.max(a, b) + 14;

  const section = (title: string) => {
    doc.rect(MARGIN, y, width, 16).fill("#f1ece2");
    doc.font("Helvetica-Bold").fontSize(8.5).fillColor("#111111").text(title, MARGIN + 6, y + 4, { width: width - 12 });
    y += 20;
  };
  const row = (code: string, label: string, value: number, bold = false) => {
    doc.font(bold ? "Helvetica-Bold" : "Helvetica").fontSize(9.5).fillColor("#111111");
    doc.fillColor("#888888").text(code, MARGIN + 6, y, { width: 44 }).fillColor("#111111");
    doc.text(label, MARGIN + 52, y, { width: width - 170 });
    const h = doc.heightOfString(label, { width: width - 170 });
    doc.text(`RM ${money(value)}`, A4.width - MARGIN - 110, y, { width: 104, align: "right" });
    y += Math.max(h, 12) + 5;
    doc.moveTo(MARGIN, y - 2).lineTo(A4.width - MARGIN, y - 2).lineWidth(0.3).strokeColor("#dddddd").stroke();
  };

  section("B. EMPLOYMENT INCOME, BENEFITS AND LIVING ACCOMMODATION");
  row("B1(a)", "Gross salary, wages or leave pay (including overtime pay)", ea.B1a);
  row("B1(b)", "Fees (including director fees), commission or bonus", ea.B1b);
  row("B1(c)", "Gross tips, perquisites, awards or allowances", ea.B1c);
  row("B1(d)", "Income tax borne by the employer", ea.B1d);
  row("B2", "Compensation for loss of employment", ea.B2);
  row("B3", "Benefits in kind", ea.B3);
  row("B4", "Value of living accommodation provided", ea.B4);
  row("", "TOTAL", ea.totalIncome, true);
  y += 6;
  section("D. TOTAL DEDUCTION");
  row("D1", "Monthly tax deductions (MTD / PCB) remitted to LHDN", ea.D1);
  row("D2", "CP38 deductions", ea.D2);
  row("D3", "Zakat paid via salary deduction", ea.D3);
  y += 6;
  section("E. CONTRIBUTIONS PAID BY EMPLOYEE");
  row("E1", "Employees Provident Fund (KWSP)", ea.E1);
  row("E2", "SOCSO and EIS (PERKESO)", ea.E2);

  y += 24;
  doc.font("Helvetica").fontSize(8.5).fillColor("#555555").text(`Date: ${fmt(new Date())}`, MARGIN, y);
  doc.text("Officer in charge: ______________________", A4.width - MARGIN - 220, y, { width: 220, align: "right" });

  drawFooters(doc, footer ?? `${ea.employer.name} · Generated by Crewly`);
  doc.end();
  return done;
}
